#!/usr/bin/bash
  
dnf update -y
dnf install -y dnf-plugins-core
dnf config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
dnf install -y terraform
terraform -v
terraform -install-autocomplete
